
CREATE TABLE users (
  username TEXT PRIMARY KEY,
  password TEXT NOT NULL,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  image_url TEXT NOT NULL DEFAULT 'https://express-friender-mj.s3.us-west-1.amazonaws.com/default-friender-image.jpg',
  hobbies TEXT NOT NULL,
  interests TEXT NOT NULL,
  location VARCHAR(5) NOT NULL,
  friend_radius INTEGER NOT NULL,
  last_searched TIMESTAMP WITH TIME ZONE);

CREATE TABLE messages (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  from_username TEXT NOT NULL REFERENCES users,
  to_username TEXT NOT NULL REFERENCES users,
  body TEXT NOT NULL,
  sent_at TIMESTAMP WITH TIME ZONE NOT NULL,
  read_at TIMESTAMP WITH TIME ZONE);

CREATE TABLE viewed_users (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  viewing_username TEXT NOT NULL REFERENCES users,
  viewed_username TEXT NOT NULL REFERENCES users,
  liked BOOLEAN NOT NULL);

CREATE TABLE friends (
  username1 TEXT NOT NULL REFERENCES users,
  username2 TEXT NOT NULL REFERENCES users,
  PRIMARY KEY (username1, username2));

